name: 同步并创建 Release

# 触发条件：当收到名为 "create-release-tag" 的 repository_dispatch 事件时
on:
  repository_dispatch:
    types: [create-release-tag]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v4

      - name: 提取传递的数据
        # 从事件的 payload 中提取 tag 和 message
        id: payload_data
        run: |
          echo "tag_name=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          echo "release_body=${{ github.event.client_payload.message }}" >> $GITHUB_ENV

      - name: 创建 Release
        # 使用官方的 create-release action
        uses: actions/create-release@v1
        env:
          # 这个 Action 需要 GITHUB_TOKEN 来获得创建 Release 的权限
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Release 对应的 Tag 名称，从上一步的环境变量中获取
          tag_name: ${{ env.tag_name }}
          
          # Release 的名称/标题，我们直接用 Tag 名称
          release_name: Release ${{ env.tag_name }}
          
          # Release 的详细描述内容，我们用源仓库的 commit message
          body: |
            这是从自动化博客部署源仓库自动同步的发布。
            
            源提交信息:
            > ${{ env.release_body }}
            
            *由 GitHub Actions 自动创建*
            
          # 设置为 false，表示这是一个稳定版 Release
          draft: false
          
          # 设置为 false，表示不是预发布版
          prerelease: false